name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, JC-ICHT]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore FileWatcherService.csproj

      - name: Build and Publish to temp
        run: dotnet publish FileWatcherService.csproj -c Release -o C:\Services\FileWatcherService_temp

      - name: Stop Windows Service
        run: Stop-Service -Name "FileWatcherService" -Force -ErrorAction SilentlyContinue

      - name: Copy files to production
        run: Copy-Item -Path "C:\Services\FileWatcherService_temp\*" -Destination "C:\Services\FileWatcherService\" -Recurse -Force -Exclude "appsettings.json"

      - name: Start Windows Service
        run: Start-Service -Name "FileWatcherService"
